@startuml
class DockingStation {
    - id: int
    - dockingStationLocation: (double, double)
    - stationType: String
    - slots: ParkingSlot[]
    - terminal: Terminal
    - on_service: boolean
    + earnCredit()
}

class ParkingSlot {
    - dockingStationId: int
    - id: int
    - status: SlotStatus
    - bike: Bicycle
    + setBicycle()
    + removeBicycle()
}

class Bicycle {
    - bicycleId: int
    - bicycleLocation: (double, double)
    - status: String
    + Bicycle()
}

class MechanicalBicycle {

}

class ElectricalBicycle {

}

class User {
    - id: int
    - name: String
    - userLocation: (double, double)
    - creditCard: CreditCard
    - registrationCard: RegistrationCard
    - timeCreditBalance: int
    - totalChargeBalance: double
}

class CreditCard {
    - number: String
    - expirationDate: Date
}

class RegistrationCard {
    - CardType: String
    - timeCreditEarned: int
    + getCardType()
}

class terminal {
    + calculateCost()
}

DockingStation --> ParkingSlot
ParkingSlot --> Bicycle
Bicycle --> MechanicalBicycle
Bicycle --> ElectricalBicycle
User --> CreditCard
User --> RegistrationCard
@enduml